### ISSUE TITLE
无法上传数据

### ISSUE THREAD

**Issue by NormalMike** [milkycandy/RotaenoUploader#1]
已使用所有解决报错方法仍无法正常使用
![Screenshot_20240717_001429_cn milkycandy rotaenoupdater](https://github.com/user-attachments/assets/69064cfc-60bf-402c-b0f6-2a65af5f1842)

**Comment by milkycandy** [comment]
你好，感谢你的反馈。请问你是否尝试过在右上角设置中关闭“尝试绕过data访问限制”开关？

**Comment by NormalMike** [comment]
尝试过

**Comment by milkycandy** [comment]
关闭那个开关的同时使用SAF模式也不行吗？

**Comment by NormalMike** [comment]
不行，因为我是鸿蒙（对标安卓12）的版本

**Comment by NormalMike** [comment]
![Uploading Screenshot_20240717_002852_cn.milkycandy.rotaenoupdater.jpg…]()

**Comment by milkycandy** [comment]
您用其他文件管理器App能找到/storage/emulated/0/Andro​id/data/com.xd.rotaeno.tapio/files/RotaenoLC/.userdata这个文件吗？

**Comment by milkycandy** [comment]
您用其他文件管理器App能找到/storage/emulated/0/Andro​id/data/com.xd.rotaeno.tapcn/files/RotaenoLC/.userdata这个文件吗

**Comment by milkycandy** [comment]
您设备的“关于手机”里是不是还有一个安全补丁日期？

**Comment by NormalMike** [comment]
有一个叫安全补丁标签的

**Comment by milkycandy** [comment]
请问日期是？

**Comment by NormalMike** [comment]
2024年3月1日

**Comment by milkycandy** [comment]
你好，今天更新了Shizuku模式，应该可以解决此问题。
